config/routes.rb
Rails.application.routes.draw do

  root 'event_home#home'

  resources :users, only: [:show, :index]
  resources :events

  devise_for :users, controllers: { sessions: "users/sessions" }, path: "auth",
              path_names: { sign_in: 'login', sign_out: 'logout' }

  get 'event_home/home'
  get 'event_home/about'

  post '/invite', to: 'users#invite'

end

app/models/event.rb
class Event < ActiveRecord::Base

  scope :upcoming, -> { where(:date >= :presentTime, presentTime: Time.now.to_date ) }
  scope :past,     -> { where(:date <= :presentTime, presentTime: Time.now.to_date ) }

  belongs_to :creator, :class_name => "User"

  has_many :invitations, :foreign_key => "attended_event_id"
  has_many :attendees, through: :invitations

  validates :title,       presence: true
  validates :description, presence: true, length: { maximum: 500 }
  validates :location,    presence: true
  validates :date,        presence: true

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :attendee, :class_name => "User"
  belongs_to :attended_event, :class_name => "Event"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :created_events, :foreign_key => "creator_id", :class_name => "Event"

  has_many :invitations, :foreign_key => "attendee_id"
  has_many :attended_events, through: :invitations

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/event_home_controller.rb
class EventHomeController < ApplicationController

  def home
    @events = Event.all
    @user = current_user
  end

  def about
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!

  def show
    @event = Event.find(params[:id])
    @users = Event.attendee_id.all
  end

  def index
    @events = Event.all
  end

  def only
    @users = Event.attendee_id.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(events_params)
    if @vent.save
      flash[:success] = "Event '#{@post.title}' created!"
      redirect_to root_path
    else
      render 'new'
    end
  end


  private

  def events_params
    params.require(:event).permit(:title, :description, :date, :location)
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :event_creator, only: :invite

  def show
    @user = User.find(params[:id])
    @events = @user.created_events
    @upcoming_events = @user.attended_events.upcoming
    @past_events = @user.attended_events.past
  end

  def index
    @user = User.all
  end

  def invite
    user_invited = User.find(params[:user_id])
    event_user_invited_to = Event.find(params[:event_id])
    user_invited.attended_events << event_user_invited_to
    redirect_to @event
  end

  private

  def event_creator
    unless current_user?(Event.find(params[:event_id]).creator)
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_home_helper.rb
module EventHomeHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event_home/about.html.erb
<h1>About Eventor</h1>
<p>
  We have all the private events that you want to store and keep a secret from!
</p>

app/views/event_home/home.html.erb
<h1>Eventor</h1>
<%= link_to "About Us", event_home_about_path %>
<br>
<p>All private events hosted here!</p>

Come register and host your private events!
<br>
<%= link_to "Create an Event", new_event_path %>

<br>
<br>

<% if user_signed_in? %>
  <%= link_to "Check Profile", user_path(@user) %>
<% else %>
  <%= link_to "Have an account? Login here!", new_user_session_path %>
  <br>
  <%= link_to "If not, Sign up for free now!", new_user_registration_path %>
<% end %>

app/views/events/index.html.erb
<h2>All Events</h2>

<p>
  <% @events.each do |e| %>
    <%= e.title %>
  <% end %>
</p>

app/views/events/new.html.erb
<h2>Create Event</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@event) do |f| %>
      <ul>
        <% @event.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>

      <%= f.label :title, "Event Name" %><br>
      <%= f.text_field :title %><br>

      <%= f.label :description, "Describe the event!" %><br>
      <%= f.text_area :description %><br>

      <%= f.label :location, "Where?" %><br>
      <%= f.text_area :location %><br>

      <%= f.label :date, "Date" %><br>
      <%= f.date_field :date %><br>

      <%= f.submit "Create", class: "btn btn-primary" %>

    <% end %>

  </div>
</div>

app/views/events/show.html.erb
<h2>Event Information</h2>

<h3><%= @event.title %></h3>
by <h4><%= @event.creator %>
<br>
<p><%= @event.description %></p>

<h3>List of Attendees</h3>
<p>
  <%= attendees.each do |a| %>
    <%= a.name %>
  <% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eventor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h2><%= @user.name %></h2>

<p>
  This is your profile stats<br>
  Email: <%= @user.email %>
  <br>
  All events created:
  <br>
  <% @events.each do |e| %>
    <%= e.created_events.title %>
    <br>
  <% end %>
</p>

<h4>Upcoming Events</h4>
<ul>
  <% if @upcoming_events.any? %>
    <%= @upcoming_events.each do |u| %>
      <li><%= u.title %></li>
    <% end %>
  <% else %>
    <p>No Upcoming Events</p>
  <% end %>
</ul>
<br>

<h4>Previous Events</h4>
<ul>
  <%# if @past_events.any? %>
    <%# @past_events.each do |p| %>
      <li><%# p.title %></li>
    <%# end %>
  <%# else %>
    <p>No Past Events</p>
  <%# end %>
</ul>


<%= link_to "Home Page", root_path %>